# Generated by Django 2.1 on 2018-08-12 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eduflox.agents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=25, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('mobile_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid mobile number.', regex='^\\d{11}$')], verbose_name='Mobile No')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Street')),
                ('city', models.CharField(max_length=25, verbose_name='City')),
                ('state', models.CharField(max_length=25, verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, unique=True, verbose_name='Invitee Email')),
                ('token', models.CharField(default=eduflox.agents.models.create_token, max_length=75, unique=True, verbose_name='Token')),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe', models.CharField(max_length=75, verbose_name='Add CPE')),
                ('cpe_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='School')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('district', models.CharField(max_length=25, verbose_name='District')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='School Code')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.School')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='request_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.ServiceRequest'),
        ),
    ]
